version: '3'
services:
  web-server:
    hostname: pavelrrr.dev
    build: /docker
    restart: always
    volumes:
      - './files/dynamic:/var/www/html/'
    ports:
      - "8080:80"

  web-server-1:
    image: nginx
    restart: always
    volumes:
      - './files/static:/etc/nginx/data/www/'
      - './confNginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "8070:80" 

  db:
    image: mysql:8.0.19
    container_name: libDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './database:/docker-entrypoint-initdb.d'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8020:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
volumes:
  mysql-data: